### ISSUE TITLE
[BUG] Sometimes it records the wrong screen

### ISSUE THREAD

**Issue by tsuza** [dec05eba/gpu-screen-recorder-issues#89]
**Describe the bug**
Recently it has started to record the wrong screen ( my second monitor ) quite often. I can't tell whether it's a bug that has been introduced recently or it's some weird interaction with Marvel Rivals.

**To Reproduce**
Using `systemd service` to start the replay and `killall -SIGUSR1 gpu-screen-recorder` to save it, with the following settings:

```
WINDOW=DP-1
CONTAINER=mkv
CODEC=av1
AUDIO_CODEC=opus
AUDIO_DEVICE=default_output
SECONDARY_AUDIO_DEVICE=default_input
REPLAYDURATION=60
OUTPUTDIR=/home/suza/Videos/Replay/
MAKEFOLDERS=yes
KEYINT=2
ENCODER=gpu
RESTORE_PORTAL_SESSION=yes
```

**Screenshots**

**Desktop (please complete the following information):**
 - X11 or Wayland: Wayland
- Desktop environment/Window Manager: Gnome 47
 - Distro: CachyOS
 - GPU: RTX 4060ti
 - Version (latest flatpak version, aur or source): AUR 4.3.3

**Additional context**
If it disable it, change the display that it's tracking, change it back and then enable it, then it works. Though, on reboot ( if not even earlier ), it happens again.

- [ ] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [ ] I use a laptop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment]
>AUR 4.3.3
Are you sure that's the version? that's 2 months outdated. Are you using the wrong gpu screen recorder package? the gpu screen recorder package was renamed from gpu-screen-recorder-git to gpu-screen-recorder a while ago

**Comment by dec05eba** [comment]
Can you run `sudo drm_info > log1.txt` when you have both monitors connected, and then disconnect the first monitor and run `sudo drm_info > log2.txt` and upload both files here? (install drm_info from aur).

**Comment by tsuza** [comment]
I'm using `gpu-screen-recorder`, yep. However, I do have to apologize on that front since I was under the impression that `pacman -Syu` would also update the AUR packages, which is not the case ( oops, I've been using Arch only for two months ). So yeah, I've been running an older version without me knowing. Nevertheless, it's weird that it didn't happen before. I'll update it and report back if it happens again.

Here are the log files as requested:
- Log file with both monitors connected: [log1.txt](https://github.com/user-attachments/files/18391378/log1.txt)
- Log file with the main monitor plugged off: [log2.txt](https://github.com/user-attachments/files/18391381/log2.txt)

**Comment by dec05eba** [comment]
Yeah you have to run `yay -Syu` (or paru if you use that) instead.
Hmm that log seems weird. Can you have both of your monitors connected and run `gpu-screen-recorder --info`? you have one display port monitor and one hdmi monitor, so it shouldn't accidentally capture the wrong one

**Comment by tsuza** [comment]
section=system_info
display_server|wayland
supports_app_audio|yes
is_steam_deck|no
section=gpu_info
vendor|nvidia
card_path|/dev/dri/card0
section=video_codecs
h264
h264_software
hevc
hevc_hdr
hevc_10bit
av1
av1_hdr
av1_10bit
section=capture_options
DP-1|1920x1080
HDMI-A-2|1920x1080
portal

**Comment by dec05eba** [comment]
I have a guess what the issue is. Recording starts and it starts recording on the correct monitor but then monitors are reconfigurated and the ids of the monitors swap place and it changes to record the other monitor. Maybe an nvidia driver update or gnome update did this. You can fix this by using desktop portal (`WINDOW=portal`) for now.

**Comment by dec05eba** [comment]
I did a quick fix now.

**Comment by dec05eba** [comment]
I did a quick fix now and pushed it to aur. Please update to the latest version of `gpu-screen-recorder` (version r940.5baa4b8) and also restart the systemd service (`systemctl restart --user gpu-screen-recorder`) and try if it still happens.

**Comment by tsuza** [comment]
Got it, thanks for being so quick. I'll let you know in the coming days if it still happens or not.

**Comment by tsuza** [comment]
Since I've updated it, Marvel Rivals has been crashing pretty frequently. Disabling it made it stop

**Comment by dec05eba** [comment]
Im pretty sure thats unrelated to the update. You can downgrade to the previous version you were using and see if it still crashes.

**Comment by dec05eba** [comment]
Run `sudo dmesg > log.txt` after a crash and post the output here. It can be a driver bug. Many people using arch/cachyOS have recently have had crashes in games, sometimes when recording (with any application) sometimes not

**Comment by tsuza** [comment]
Aha, I see. It wasn't happening before so I assumed it might have been related to it, since it's the only thing I've updated.

Here is the log file as requested:  [log.txt](https://github.com/user-attachments/files/18403472/log.txt)

**Comment by dec05eba** [comment]
Ok there is no crash there, I assume you will have to run that command right after the crash happens instead.

**Comment by tsuza** [comment]
Alrighty, I'll try again next time it happens. I have to specify that it technically froze and I had to manually close the application, which is why it's most likely not showing up under the logs.

**Comment by dec05eba** [comment]
https://www.reddit.com/r/linux_gaming/comments/1hlvxng/issues_with_marvel_rivals_freezing/ maybe it's related to this issue. When you are recording its using more vram so it might make it more likely to happen

**Comment by dec05eba** [comment]
But anyways, if you see a crash then dont close gpu screen recorder. Run `nvtop` to see how much ram and vram gpu screen recorder is using. Which you can then compare to how much ram/vram its using after you restart gpu screen recorder and wait 60 seconds (until the replay buffer is full)

**Comment by tsuza** [comment]
Got it, thanks. I'll let you know in a day or two.

**Comment by tsuza** [comment]
I get a bunch of `NVRM: VM: invalid mmap` in the log file right, and it should be right after the freeze. I'll try to downgrade and see if it helps.

**Comment by dec05eba** [comment]
Can you show the whole log file? there can be some other info there

**Comment by tsuza** [comment]
Sure, but it's mostly just that:  [log.txt](https://github.com/user-attachments/files/18417698/log.txt)

**Comment by dec05eba** [comment]
https://github.com/ValveSoftware/Proton/wiki/Changelog maybe this latest update fixes the issues you had in marvel rivals

**Comment by dec05eba** [comment]
Does the issue with incorrect screen still happen? also did you try if it crashes the game with the new version but not old version? otherwise its an issue caused by the driver or the game is very sensitive to vram increase and it also happens with other screen recorders

**Comment by tsuza** [comment]
I've been slightly busy due to exams, so I haven't had the chance to play much. Sorry! Moreover, since I played ranked, I preferred to avoid crashing in-game.

It seems to work fine in any other game, so it might be related to VRAM and / or something else while you're recording ( I heard some mentions about Nvidia Reflex causing crashes, so it might be a weird interaction ) specifically on Marvel Rivals. 

I'll test it once I have more time and let you know. Feel free to close the issue if you want in the meantime.

**Comment by dec05eba** [comment]
Yeah i'll do that since the issue related to wrong monitor should be fixed I believe at least. If you notice an issue with crashing that doesn't happen in obs studio for example with nvenc option then you can create a new issue related to that crash instead.

**Comment by tsuza** [comment]
The issue ( the wrong screen being recorder ) seems to persist even on `5.1.0`, and I can reproduce it pretty frequently with Marvel Rivals. I'll switch to Portal as you've suggested, but seemingly the fix, at least in my case, has not fixed it ( or at least fully ). Just letting you know.
